name: Main workflow

on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 5

jobs:
  plugin_test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system packages on Ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get install curl

      - name: Install system packages on macOS
        if: ${{ runner.os == 'macOS' }}
        run: brew install coreutils

      - name: Install rtx
        uses: jdxcode/rtx-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir -p ~/.local/share/rtx/plugins
      - run: ln -s $PWD ~/.local/share/rtx/plugins/nodejs
      - run: rtx i nodejs@lts
      - run: rtx x nodejs@lts -- node -v
